function sigmaetagraph(ILDS1, ymatrix1)
%CREATEFIGURE(ILDS1,YMATRIX1)
%  ILDS1:  bar xvector
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 06-Jul-2013 17:27:18

% Create figure
figure1 = figure('Name',...
    'Comparison between $\sigma(\eta(x))$ of each algorithm and instances sets.');

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'100','200','300','400','500','600','700','800','900','1000'},...
    'XTick',[1 2 3 4 5 6 7 8 9 10],...
    'Position',[0.100574712643678 0.11 0.799808429118773 0.815],...
    'FontWeight','bold',...
    'FontSize',16);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 10.5]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(ILDS1,ymatrix1,'BarWidth',1,'Parent',axes1);
set(bar1(1),'DisplayName','ILDS');
set(bar1(2),'DisplayName','BFS');
set(bar1(3),'DisplayName','DFS');

% Create xlabel
xlabel('$x$','Interpreter','latex','FontWeight','bold','FontSize',20,...
    'FontAngle','italic');

% Create ylabel
ylabel('$\sigma(\eta(x))$','Interpreter','latex','FontWeight','bold',...
    'FontSize',24);

% Create title
title('Comparison between $\sigma(\eta(x))$ of each algorithm and instances sets.',...
    'Interpreter','latex',...
    'FontSize',20);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.905172413793103 0.787844328438705 0.0886015325670498 0.137067395264117],...
    'FontSize',14);

