function createfigure(ymatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 07-Jul-2013 22:27:40

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'YTick',[0 0.05 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.45],...
    'YMinorGrid','on',...
    'YGrid','on',...
    'XTickLabel',{'100','200','300','400','500','600','700','800','900','1000'},...
    'XTick',[1 2 3 4 5 6 7 8 9 10],...
    'Position',[0.0707251566696508 0.11 0.810205908683975 0.815],...
    'GridLineStyle','-.');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.5 10.5]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'BarWidth',1,'Parent',axes1);
set(bar1(1),'DisplayName','ILDS');
set(bar1(2),'DisplayName','BFS');
set(bar1(3),'DisplayName','DFS');

% Create xlabel
xlabel('$x$','Interpreter','latex','FontSize',24);

% Create ylabel
ylabel('$\upsilon(x)$','Interpreter','latex','FontSize',24);

% Create title
title('Demonstration of cost benefit ratio for the ILDS, BFS and DFS',...
    'FontSize',24);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.893822924450824 0.787493469174503 0.0890778871978514 0.136755485893417],...
    'FontSize',16);

